/// <reference types="node" />
import ControllerBase from './controller-base';
import { Color, LightProbeGroup, Node, Vec3 } from 'cc';
import PositionGizmo from '../transform/position-gizmo';
import { IControlMouseEvent } from '../../../defines';
import LightProbeEditModeListener from '../listener/light-probe-edit-mode-listener';
import GizmoOperationEventListener from '../listener/gizmo-operation-event-listener';
import { ISceneMouseEvent } from '../../../../../../../@types/private';
import SimpleSet from '../../../utils/set-util';
import type GizmoBase from '../gizmo-base';
declare type NodeProbe = {
    node: Node;
    probe: Vec3;
};
export default class LightProbeController extends ControllerBase implements LightProbeEditModeListener, GizmoOperationEventListener {
    targetDelegate: TargetDelegate<LightProbeGroup>;
    gizmo: GizmoBase;
    static ProbeColor: Color;
    static SelectedProbeColor: Color;
    static WireFrameColor: Color;
    static ConvexColor: Readonly<Color>;
    static Count: number;
    static get Name(): string;
    static LightProbeSphereName: string;
    static TetrahedronNode: Node;
    static OuterCell: Node;
    protected _lockSize: boolean;
    private _isInitialized;
    private _probePool;
    private _currentProbes;
    private _currentSelectedProbeNames;
    private _probeSphere;
    private _reuseAbleMesh?;
    private _reuseAbleMaterial;
    private _gizmoEventListener;
    private _gizmoEventListenerIndex;
    private _shouldDiffOnNextUpdate;
    private _editMode;
    private _lightProbeInfo;
    private _positionNode;
    positionGizmo: PositionGizmo;
    get currentProbesArray(): {
        key: string;
        nodeProbe: NodeProbe;
    }[];
    get currentProbeNames(): Set<string>;
    get probeSphere(): Node;
    constructor(rootNode: Node, targetDelegate: TargetDelegate<LightProbeGroup>, gizmo: GizmoBase);
    initShape(): void;
    tempAdjustSizeV3: Vec3;
    delta: number;
    adjustControllerSize(): void;
    static debounceUpdate: NodeJS.Timeout | null;
    updateController(): void;
    updateProbes(): void;
    updateLines(updateInfo?: boolean): void;
    updateWireframe(): Set<string>;
    updateConvex(indicesString?: Set<string>): number[];
    updateLightProbeInfo(): void;
    createProbeNode(probe: Vec3): Node;
    updateProbesColor(): void;
    updateLinesNode(node: Node, position: Vec3, vertices: Vec3[], indices: number[], color?: Color): void;
    static TetrahedronLines: number[];
    static OuterCellLines: number[];
    releaseProbeNodes(nodeProbes: NodeProbe[]): void;
    updateNodeTransformInfo(node: Node): void;
    protected onShow(): void;
    protected onHide(): void;
    protected onMouseDown(event: IControlMouseEvent): void;
    protected onMouseMove(event: IControlMouseEvent): void;
    protected onMouseUp(event: IControlMouseEvent): void;
    get currentSelectedProbes(): NodeProbe[];
    protected changePositionTarget(target: Node[]): void;
    selectProbe(names: Iterable<string>): void;
    unselectProbe(names: Iterable<string>): void;
    private clearCurrentSelectedProbe;
    private updatePositionGizmo;
    lightProbeEditModeChanged(mode: boolean): void;
    boundingBoxEditModeChanged(mode: boolean): void;
    duplicateCurrentSelectedProbes(): SimpleSet<Node>;
    deleteCurrentSelectedProbes(): SimpleSet<Node>;
    clearLayer(node: Node, recursive?: boolean): void;
    restoreLayer(node: Node, recursive?: boolean): void;
    clearProbeNodesLayer(): void;
    restoreProbeNodesLayer(): void;
    diff(): NodeProbe[];
    onNotGizmoMouseDown(event: ISceneMouseEvent): void;
    onNotGizmoMouseMove(event: ISceneMouseEvent): void;
    onNotGizmoMouseUp(event: ISceneMouseEvent): void;
    shouldEmitNodes(): SimpleSet<string>;
    select(nodes: SimpleSet<Node>): void;
    selectAll(): void;
    unselect(nodes: SimpleSet<Node>): void;
    unselectAll(): void;
    currentSelectedNodes(): SimpleSet<Node>;
    lightProbeInfoChanged(): void;
    hideAllChildren(): void;
}
export interface TargetDelegate<T> {
    get target(): T;
}
export {};
//# sourceMappingURL=light-probe-controller.d.ts.map